### PR TITLE
Backup Script

### PR DESCRIPTION
**Pull request by Skillkiller**
With this pull request I want to add a backup script to automatically backup the Minecraft server. The backups are created using zip and saved to any destination using rclone.
The goal is to make the backup script dynamic and configurable. For this I have added a few new environment variables. Furthermore rclone also reads some enviroment variables.

### CODE REVIEW

**Comment by Skillkiller** [comment]
Open todos:
- [X] Test target with whitespaces
- [X] Test prre and post backup config Variable
- [X] Add hint why pre *and* post backup
- [X] Add docker-compose example

**Comment by zekroTJA** [comment]
Looks really exciting. Would be awesome too if we could later add the script also to [papermc-docker](https://github.com/zekroTJA/papermc-docker).

**Comment by Skillkiller** [comment]
Yes sure I will submit the whole thing as a pull request for the other project as well. Please check the current state and tell me if the hints in the readme are enough to set everything up.

**Comment by zekroTJA** [comment]
Looks good! What also would be awesome if there would be the possibility to run backups periodically during the runtime of the container using the script. ^^

**Comment by Skillkiller** [comment]
Unfortunately, I do not know how to implement the periodic backups. The first thing I would think of is to install a cron. But how do I get a consistent backup at runtime. Plugins or worlds could change something in the files exactly at the time of backup creation.
Do you have any ideas? Or is that a risk to take?

**Comment by zekroTJA** [comment]
Sorry, I absolutely forgot about this PR. I would take it as is for now because I also have no good Idea how to implement such an external backup system without potential corruption of world files without shutting down the server to back it up which would be kind of crappy. ^^

**Pull request merged**
